# Generated by Django 5.0.7 on 2024-08-06 09:55

import job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_apply_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(null=True, upload_to=job.models.image_upload),
        ),
    ]
